
package com.posta.crm.enums;


public enum TypeOfCompany {
    MICRO,
    PEQUEÑA,
    MEDIANA,
    GRANDE,
    LOCAL,
    REGIONAL,
    NACIONAL,
    MULTINACIONAL,
    TRANSNACIONAL,
    EXTRACCION,
    TRANSFORMACION,
    COMERCIAL,
    SERVICIOS,
    PUBLICA,
    PRIVADA,
    MIXTA,
    SOCIEDAD_ANONIMA,
    RESPONSABILIDAD_LIMITADA,
    COLECTIVA,
    COOPERATIVA,
    COMANDITARIA,
    ACCION_SIMPLIFICADA,
    ARTESANAL,
    TRADICIONAL,
    TECNOLOGIA_MEDIA,
    TECNOLOGIA_AVANZADA
    
}
